config:
  env: rd_locl
  mysql: #数据库配置
    read:
      dsn: api_w:SRsTI60fQE+RV-liaHU@tcp(127.0.0.1:3307)/?parseTime=true&loc=Asia%2FShanghai
      debug: true
  redis: #redis配置
    common:
      addr: localhost:6379
      auth: